stid=input("Enter you are ID NO:")
stname=input("Enter you are name:")
stph=int(input("Enter you are number:91+"))
stmail=input("Enter you are mail id:")
stclg=input("Enter you are clg name:")
srbr=input("Enter you are Branch:")
print("-"*50)
print("\t\t STUDENT PROFILE")
print("-"*50)
#print("\t{}\n\t{}\n\t91+{}\n\t{}\n\t{}\n\t{}".format(stid,stname,stph,stmail,stclg,srbr))
#print(stid,"\n",stname,"\n",stph,"\n",stmail,"\n",stclg,"\n",srbr)
print(stid)
print(stname)
print(stph)
print(stmail)
print(stclg)
print(srbr)
print("-"*50)
